# Generated by Django 3.1.7 on 2021-10-26 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Categorie', models.CharField(choices=[(2, 'Consommables et Equipement médicaux'), (1, 'Petite et grande chururgie'), (5, 'Produits de laboratoire'), (3, 'Materiel de la chururgie'), (6, 'Produits Dentaires'), (7, 'Tuyauterie'), (4, 'Produits CONWELL')], default=1, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('nom', 'tel')},
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('a_payer', models.PositiveIntegerField(default=0, editable=False)),
                ('payee', models.PositiveIntegerField(default=0.0, editable=False)),
                ('reste', models.PositiveIntegerField(default=0.0, editable=False)),
                ('uncommited', models.PositiveIntegerField(default=0, editable=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('unite', models.CharField(max_length=50, verbose_name='unité de mesure')),
                ('unite_sortant', models.CharField(max_length=50)),
                ('rapport', models.FloatField(default=1)),
                ('quantite', models.FloatField(default=0, editable=False)),
                ('prix_vente', models.FloatField(default=0)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('prix_achat', models.FloatField(editable=False, null=True)),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantite', models.FloatField()),
                ('details', models.TextField(blank=True, null=True)),
                ('prix_achat', models.FloatField(editable=False, null=True)),
                ('prix_vente', models.FloatField(default=0, editable=False)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('somme', models.PositiveIntegerField(default=0, verbose_name='somme payée')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('validated', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.client')),
                ('commande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantite', models.FloatField()),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('details', models.TextField(blank=True, null=True)),
                ('prix_total', models.FloatField()),
                ('prix_unitaire', models.FloatField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.produit')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['produit'],
            },
        ),
    ]
